# -----------------------------------------------------------------------------
# Dataset
# -----------------------------------------------------------------------------
# List of the dataset names for training, as present in paths_catalog.py
names: 'market1501'
  
# Root directory where datasets should be used (and downloaded if not found)
root_dir: '/home/maksimovaam/reid-task'