# ---------------------------------------------------------------------------- #
# TEST
# ---------------------------------------------------------------------------- #
# Whether to evaluate the model during testing
eval: true
# Number of images per batch during test
ims_per_batch: 32
# If test with re-ranking
re_ranking: false
# Path to trained model
weight: "CLIP-ReID_RN50_Captions_rebuild_stage2_final.pth"
# Which feature of BNNeck to be used for test, before or after BNNneck
# Options: 'before' or 'after'
neck_feat: "before"
# Whether feature is normalized before test
# If yes, it is equivalent to cosine distance
feat_norm: "yes"
# Name for saving the distmat after testing
dist_mat: "dist_mat.npy"
# Load model from article
load_from_article: False
# Article name weight
article_name_weight: "Market1501_clipreid_RN50_120.pth"
